### ISSUE TITLE
Some lines are truncated in zsh.nanorc

### ISSUE THREAD

**Issue by blakelead** [AbhishekGhosh/nano-syntax-highlighting-iNano-#1]
Hi,

First of all, thank you for your helpful tutorial & nanorc files.

I noticed that zsh.nanorc has truncated lines at lines 8 and 9. I managed to get the correct file because the issue was introduced by the second commit of this file, but for others might not have the idea or patience to find what is wrong with this file.

(I haven't check all the files, there may be other issues)

Adel

**Comment by AbhishekGhosh** [comment]
@Blake-Lead Thanks a lot for opening the issue and in-depth checking! You are correct, line number 8, 9 were truncated. I have quickly fixed it now from Github web UI, [please see this diff.](https://github.com/AbhishekGhosh/nano-syntax-highlighting-iNano-/commit/3a88d4d3237647abe8db6b0fb4f15fa4d4f882a9) . I will pull the whole repo, build to check it and push it. Nginx & Apache2 also demands update.

**Comment by blakelead** [comment]
You are welcome, I'm closing this issue then. Again thank you for your work, great job!
